### ISSUE TITLE
Error 'cpp' is not recognized as a command

### ISSUE THREAD

**Issue by QwertyZW** [taufique71/node-c-parser#4]
I'm not exactly sure but I think the module is expecting a command 'cpp' to be available in $PATH. I tried a global install and a local install but neither worked (nothing generated a 'cpp' script)

Here's the stack trace:

Error: Command failed: cpp ‪C:\Users\zaid\Desktop\dev\cteststuff\test.c 2fe07600-9fe7-11e6-8b03-03eb010391b8
'cpp' is not recognized as an internal or external command,
operable program or batch file.

    at ChildProcess.exithandler (child_process.js:214:12)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at maybeClose (internal/child_process.js:850:16)
    at Socket.<anonymous> (internal/child_process.js:323:11)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at Pipe._onclose (net.js:477:12)

Relevant file: https://github.com/taufique71/node-c-lexer/blob/master/lib/cpp-unit.js

**Comment by taufique71** [comment]
Yes, the module depends on GCC for pre-processor expansion. As far as I know `cpp` comes with GCC.

**Comment by QwertyZW** [comment]
Oh... that makes sense now. Should probably do something about how it's finding it, like have the module grab the path from a default config or something like that. 

If you had already built a c lexer/parser in js might as well implement a preprocessor too, such that you wouldn't have any external dependencies.  Not sure but that might be overkill.

**Comment by taufique71** [comment]
Right now I think that will be overkill. If needed anytime then it can be done. Whatever, should I close the issue?
